### ISSUE TITLE
String example

### ISSUE THREAD

**Issue by tongong** [mihirlad55/dwm-ipc#15]
The wiki mentions ARG_TYPE_STR and I assume that means one can pass a string to a function inside dwm. I tried it with spawn but that immeadiately crashed dwm after the dwm-msg command.

Could you maybe give an example for the run command with a string argument?

Sorry if this is a stupid question, I'm quite a noob regarding C.

**Comment by mihirlad55** [comment]
The `ARG_TYPE_STR` and `ARG_TYPE_PTR` argument types mean you are passing a pointer. Unfortunately, there is currently no way to send arbitrary strings to dwm. To use a command with the `ARG_TYPE_STR` or `ARG_TYPE_PTR`, you have to pass an address to a static string defined in dwm. For example, `dwm-msg run_command spawn 12341242512515` where the number is the address of a string in dwm.

The only way for these types of commands to work is if there is a way to query the addresses of these strings defined in dwm since their addresses would change every time dwm is launched.

The `dwm-msg get_layouts` command for example returns the addresses of the different layouts and `dwm-msg run_command setlayoutsafe 214124124124141` would set the layout using the address given.

If this answers your question, please close this issue.

**Comment by tongong** [comment]
Oh, that's a real pity. But nevertheless thank you for your effort.
